apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: prepare-host
spec:
  inputs:
    resources:
      - name: hetzner-ocp4
        type: git
  steps:
    - name: prepare-host
      image: quay.io/rbo/sandbox:ubi-ansible
      imagePullPolicy: Always
      command:
        - /usr/bin/bash
        - -x
        - -c
        - |
          cp -v /secret/cluster.yml hetzner-ocp4/
          cd hetzner-ocp4/
          ./pipeline/cluster-yml-to-env.sh
          source cluster.env

          ssh \
            -o StrictHostKeyChecking=no \
            -i /secret/ssh-privatekey \
            -l root \
            $HETZNER_IP \
            'cd hetzner-ocp4/ && ./ansible/01-prepare-host.yml'
            
      volumeMounts:
      - name: hetzner-ocp4-pipeline
        mountPath: "/secret"
        readOnly: true
  volumes:
    - name: hetzner-ocp4-pipeline
      secret:
        secretName: hetzner-ocp4-pipeline