apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: hetzner-ocp4
spec:
  resources:
  - name: workspace
    type: git
  tasks:
    - name: reset-hetzner-server
      taskRef:
        name: reset-hetzner-server
      resources:
        inputs:
        - name: hetzner-ocp4
          resource: workspace
    - name: init-server
      taskRef:
        name: init-server
      resources:
        inputs:
        - name: hetzner-ocp4
          resource: workspace